name: Mein erster Workflow

# Definiert, wann der Workflow starten soll
on:
  push:               # Startet bei jedem "git push"
  workflow_dispatch:  # Erm√∂glicht den manuellen Start-Button bei GitHub

jobs:
  beispiel_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hallo Welt sagen
        run: echo "Der Workflow funktioniert!"
